apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxembourg-population-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: luxembourg-population
  template:
    metadata:
      labels:
        app: luxembourg-population
    spec:
      containers:
      - name: luxembourg-population-container
        image: luxembourg-population-service
        imagePullPolicy: Never  
        ports:
        - containerPort: 3000