apiVersion: v1
kind: Service
metadata:
  name: luxembourg-population-service
spec:
  type: LoadBalancer
  selector:
    app: luxembourg-population
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000  
